apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nextcloud
  pass_credentials_all: false
  password: ""
  url: https://nextcloud.github.io/helm/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nextcloud-aio
  pass_credentials_all: false
  password: ""
  url: https://nextcloud.github.io/all-in-one/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ingress-nginx
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/ingress-nginx
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: collabora
  pass_credentials_all: false
  password: ""
  url: https://collaboraonline.github.io/online/
  username: ""
