apiVersion: v1
kind: Secret
metadata:
  name: talk-hpb-secrets
  namespace: nextcloud
type: Opaque
stringData:
  TURN_SECRET: 0d3e50717c9fff2263babeec3a8b3b86e33252822162642cb35a758087fb76e0
  SIGNALING_SECRET: 495bc2e029ac8e5cd461a910bb7f48d10a10ece20e4de36f4b3ea8ed7cea029f
  INTERNAL_SECRET: 90474c17177e328fc2289a1004354f9d7264aab953f642b23e3a4eac7e7b0fb7
