apiVersion: v1
kind: Secret
metadata:
   name: redis-auth
   namespace: nextcloud
   labels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: nextcloud
type: Opaque
stringData:
   REDIS_PASSWORD: "2EWE0goes0Sovereign2!5"
